@echo off
echo Adding environment variables to Vercel...

echo Adding DATABASE_URL...
echo postgresql://neondb_owner:npg_xjLTPW7FDQl8@ep-shiny-grass-abx87srp-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require | vercel env add DATABASE_URL production

echo Adding JWT_SECRET...
echo 0a8b3ba155a5a8f7ab6ef125c7241dbb77a94e750f13f2b9 | vercel env add JWT_SECRET production

echo Adding CORS_ORIGIN...
echo http://localhost:3000,https://excel-management-rho.vercel.app | vercel env add CORS_ORIGIN production

echo Adding CRED_ENC_KEY...
echo fc9a6a96031d25092993287641aae55a23715e40a9358187525537c25895a678 | vercel env add CRED_ENC_KEY production

echo Adding IONOS_SFTP_HOST...
echo access820600719.webspace-data.io | vercel env add IONOS_SFTP_HOST production

echo Adding IONOS_SFTP_PORT...
echo 22 | vercel env add IONOS_SFTP_PORT production

echo Adding IONOS_SFTP_USERNAME...
echo acc805539974 | vercel env add IONOS_SFTP_USERNAME production

echo Adding IONOS_SFTP_PASSWORD...
echo Tech_ezm@252025! | vercel env add IONOS_SFTP_PASSWORD production

echo Adding IONOS_SFTP_BASE_PATH...
echo /uploads | vercel env add IONOS_SFTP_BASE_PATH production

echo Adding NODE_ENV...
echo production | vercel env add NODE_ENV production

echo All environment variables added successfully!